// HTTP API function names
// Used with perfect hash for O(1) string → enum dispatch

enum HttpFunction : string {
  backendGetConfig,
  backendGetPPSState,
  backendManualPayout,
  backendPoolLuck,
  backendQueryCoins,
  backendQueryFoundBlocks,
  backendQueryPayouts,
  backendQueryPoolBalance,
  backendQueryPoolStats,
  backendQueryPoolStatsHistory,
  backendQueryPPLNSAcc,
  backendQueryPPLNSPayouts,
  backendQueryPPSHistory,
  backendQueryPPSPayouts,
  backendQueryPPSPayoutsAcc,
  backendQueryProfitSwitchCoeff,
  backendQueryUserBalance,
  backendQueryUserStats,
  backendQueryUserStatsHistory,
  backendQueryWorkerStatsHistory,
  backendUpdateConfig,
  backendUpdateProfitSwitchCoeff,
  complexMiningStatsGetInfo,
  instanceEnumerateAll,
  userAction,
  userActivate2faInitiate,
  userAdjustInstantPayoutThreshold,
  userChangeEmail,
  userChangeFeePlan,
  userChangePasswordForce,
  userChangePasswordInitiate,
  userCreate,
  userCreateFeePlan,
  userCreateForce,
  userDeactivate2faInitiate,
  userDeleteFeePlan,
  userEnumerateAll,
  userEnumerateFeePlan,
  userGetCredentials,
  userGetSettings,
  userLogin,
  userLogout,
  userQueryFeePlan,
  userQueryMonitoringSession,
  userRenewFeePlanReferralId,
  userResendEmail,
  userUpdateCredentials,
  userUpdateFeePlan,
  userUpdateSettings
}
